/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedHealthScoreRouteImport } from './routes/_authenticated.health-score'
import { Route as AuthenticatedEmotionsRouteImport } from './routes/_authenticated.emotions'
import { Route as AuthenticatedDiaryRouteImport } from './routes/_authenticated.diary'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedChatbotRouteImport } from './routes/_authenticated.chatbot'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated.activities'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'
import { Route as AuthenticatedActivitiesActivityIdxRouteImport } from './routes/_authenticated.activities.$activityIdx'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHealthScoreRoute =
  AuthenticatedHealthScoreRouteImport.update({
    id: '/health-score',
    path: '/health-score',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmotionsRoute = AuthenticatedEmotionsRouteImport.update({
  id: '/emotions',
  path: '/emotions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiaryRoute = AuthenticatedDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatbotRoute = AuthenticatedChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivitiesActivityIdxRoute =
  AuthenticatedActivitiesActivityIdxRouteImport.update({
    id: '/$activityIdx',
    path: '/$activityIdx',
    getParentRoute: () => AuthenticatedActivitiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activities': typeof AuthenticatedActivitiesRouteWithChildren
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/emotions': typeof AuthenticatedEmotionsRoute
  '/health-score': typeof AuthenticatedHealthScoreRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/activities/$activityIdx': typeof AuthenticatedActivitiesActivityIdxRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activities': typeof AuthenticatedActivitiesRouteWithChildren
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/emotions': typeof AuthenticatedEmotionsRoute
  '/health-score': typeof AuthenticatedHealthScoreRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/activities/$activityIdx': typeof AuthenticatedActivitiesActivityIdxRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/activities': typeof AuthenticatedActivitiesRouteWithChildren
  '/_authenticated/chatbot': typeof AuthenticatedChatbotRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diary': typeof AuthenticatedDiaryRoute
  '/_authenticated/emotions': typeof AuthenticatedEmotionsRoute
  '/_authenticated/health-score': typeof AuthenticatedHealthScoreRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/activities/$activityIdx': typeof AuthenticatedActivitiesActivityIdxRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activities'
    | '/chatbot'
    | '/dashboard'
    | '/diary'
    | '/emotions'
    | '/health-score'
    | '/profile'
    | '/activities/$activityIdx'
    | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activities'
    | '/chatbot'
    | '/dashboard'
    | '/diary'
    | '/emotions'
    | '/health-score'
    | '/profile'
    | '/activities/$activityIdx'
    | '/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/activities'
    | '/_authenticated/chatbot'
    | '/_authenticated/dashboard'
    | '/_authenticated/diary'
    | '/_authenticated/emotions'
    | '/_authenticated/health-score'
    | '/_authenticated/profile'
    | '/_authenticated/activities/$activityIdx'
    | '/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/health-score': {
      id: '/_authenticated/health-score'
      path: '/health-score'
      fullPath: '/health-score'
      preLoaderRoute: typeof AuthenticatedHealthScoreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/emotions': {
      id: '/_authenticated/emotions'
      path: '/emotions'
      fullPath: '/emotions'
      preLoaderRoute: typeof AuthenticatedEmotionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diary': {
      id: '/_authenticated/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof AuthenticatedDiaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chatbot': {
      id: '/_authenticated/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof AuthenticatedChatbotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activities/$activityIdx': {
      id: '/_authenticated/activities/$activityIdx'
      path: '/$activityIdx'
      fullPath: '/activities/$activityIdx'
      preLoaderRoute: typeof AuthenticatedActivitiesActivityIdxRouteImport
      parentRoute: typeof AuthenticatedActivitiesRoute
    }
  }
}

interface AuthenticatedActivitiesRouteChildren {
  AuthenticatedActivitiesActivityIdxRoute: typeof AuthenticatedActivitiesActivityIdxRoute
}

const AuthenticatedActivitiesRouteChildren: AuthenticatedActivitiesRouteChildren =
  {
    AuthenticatedActivitiesActivityIdxRoute:
      AuthenticatedActivitiesActivityIdxRoute,
  }

const AuthenticatedActivitiesRouteWithChildren =
  AuthenticatedActivitiesRoute._addFileChildren(
    AuthenticatedActivitiesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRouteWithChildren
  AuthenticatedChatbotRoute: typeof AuthenticatedChatbotRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiaryRoute: typeof AuthenticatedDiaryRoute
  AuthenticatedEmotionsRoute: typeof AuthenticatedEmotionsRoute
  AuthenticatedHealthScoreRoute: typeof AuthenticatedHealthScoreRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRouteWithChildren,
  AuthenticatedChatbotRoute: AuthenticatedChatbotRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiaryRoute: AuthenticatedDiaryRoute,
  AuthenticatedEmotionsRoute: AuthenticatedEmotionsRoute,
  AuthenticatedHealthScoreRoute: AuthenticatedHealthScoreRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
